In [1]:
#Import Libraries
import numpy as np
import pandas as pd



In [187]:
#Read CSV files into python
Df_1 = pd.read_csv ("C:/Users/Sdeol/Desktop/all/train_technidus_clf.csv")
Df_2 = pd.read_csv ("C:/Users/Sdeol/Desktop/all/test_technidus_clf.csv")

Df_1.head()

Df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3328 entries, 0 to 3327
Data columns (total 25 columns):
CustomerID              3328 non-null int64
Title                   21 non-null object
FirstName               3328 non-null object
MiddleName              1896 non-null object
LastName                3328 non-null object
Suffix                  1 non-null object
AddressLine1            3328 non-null object
AddressLine2            48 non-null object
City                    3328 non-null object
StateProvinceName       3328 non-null object
CountryRegionName       3328 non-null object
PostalCode              3328 non-null object
PhoneNumber             3328 non-null object
BirthDate               3328 non-null object
Education               3328 non-null object
Occupation              3328 non-null object
Gender                  3328 non-null object
MaritalStatus           3328 non-null object
HomeOwnerFlag           3328 non-null int64
NumberCarsOwned         3328 non-null int64
Num

In [188]:
#Merge Training and Testing dataset

df = pd.concat([Df_1, Df_2],ignore_index=True)

C:\Users\Sdeol\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  This is separate from the ipykernel package so we can avoid doing imports until


In [189]:
#Perfrom Exploratory Data Analysis.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11013 entries, 0 to 11012
Data columns (total 25 columns):
AddressLine1            3328 non-null object
AddressLine2            48 non-null object
AveMonthSpend           11013 non-null int64
BikeBuyer               7685 non-null float64
BirthDate               3328 non-null object
City                    3328 non-null object
CountryRegionName       11013 non-null object
CustomerID              3328 non-null float64
Education               11013 non-null object
FirstName               3328 non-null object
Gender                  11013 non-null object
HomeOwnerFlag           11013 non-null int64
LastName                3328 non-null object
MaritalStatus           11013 non-null object
MiddleName              1896 non-null object
NumberCarsOwned         11013 non-null int64
NumberChildrenAtHome    11013 non-null int64
Occupation              11013 non-null object
PhoneNumber             3328 non-null object
PostalCode              3328 no

In [190]:
df.head()

AddressLine1 AddressLine2  AveMonthSpend  BikeBuyer BirthDate City  \
0          NaN          NaN             70        1.0       NaN  NaN   
1          NaN          NaN             69        0.0       NaN  NaN   
2          NaN          NaN            102        0.0       NaN  NaN   
3          NaN          NaN             49        0.0       NaN  NaN   
4          NaN          NaN             73        0.0       NaN  NaN   

  CountryRegionName  CustomerID        Education FirstName     ...       \
0    United Kingdom         NaN       Bachelors        NaN     ...        
1            Canada         NaN       Bachelors        NaN     ...        
2            Canada         NaN       Bachelors        NaN     ...        
3     United States         NaN  Graduate Degree       NaN     ...        
4     United States         NaN      High School       NaN     ...        

  NumberCarsOwned  NumberChildrenAtHome      Occupation PhoneNumber  \
0               0                     0          Manual         NaN   
1               1                     0    Professional         NaN   
2               0                     2  Skilled Manual         NaN   
3               0                     0  Skilled Manual         NaN   
4               2                     0        Clerical         NaN   

  PostalCode  StateProvinceName  Suffix Title TotalChildren YearlyIncome  
0        NaN            England     NaN   NaN             1        35455  
1        NaN   British Columbia     NaN   NaN             0        43980  
2        NaN   British Columbia     NaN   NaN             2        57713  
3        NaN         California     NaN   NaN             1        53438  
4        NaN         Washington     NaN   NaN             1        55291  

[5 rows x 25 columns]

In [192]:
#Drop dimensions which are not useful to analysis

data=df.drop(["AddressLine1", "AddressLine2", "BirthDate", "CustomerID", "FirstName","StateProvinceName","PhoneNumber", "Suffix", "Title","LastName", "MiddleName","NumberChildrenAtHome", "City", "PostalCode"], axis=1)
data.head()

AveMonthSpend  BikeBuyer CountryRegionName        Education Gender  \
0             70        1.0    United Kingdom       Bachelors       M   
1             69        0.0            Canada       Bachelors       M   
2            102        0.0            Canada       Bachelors       M   
3             49        0.0     United States  Graduate Degree      F   
4             73        0.0     United States      High School      M   

   HomeOwnerFlag MaritalStatus  NumberCarsOwned      Occupation  \
0              1             M                0          Manual   
1              0             S                1    Professional   
2              1             M                0  Skilled Manual   
3              1             M                0  Skilled Manual   
4              0             M                2        Clerical   

   TotalChildren  YearlyIncome  
0              1         35455  
1              0         43980  
2              2         57713  
3              1         53438  
4              1         55291

In [193]:
#Save Clean data

data.to_csv ("C:/Users/Sdeol/Desktop/all/bikebuyer2.csv")

In [194]:

df= pd.read_csv ("C:/Users/Sdeol/Desktop/all/bikebuyer2.csv")

In [195]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11013 entries, 0 to 11012
Data columns (total 12 columns):
Unnamed: 0           11013 non-null int64
AveMonthSpend        11013 non-null int64
BikeBuyer            7685 non-null float64
CountryRegionName    11013 non-null object
Education            11013 non-null object
Gender               11013 non-null object
HomeOwnerFlag        11013 non-null int64
MaritalStatus        11013 non-null object
NumberCarsOwned      11013 non-null int64
Occupation           11013 non-null object
TotalChildren        11013 non-null int64
YearlyIncome         11013 non-null int64
dtypes: float64(1), int64(6), object(5)
memory usage: 1.0+ MB


In [196]:
df.head()

Unnamed: 0  AveMonthSpend  BikeBuyer CountryRegionName        Education  \
0           0             70        1.0    United Kingdom       Bachelors    
1           1             69        0.0            Canada       Bachelors    
2           2            102        0.0            Canada       Bachelors    
3           3             49        0.0     United States  Graduate Degree   
4           4             73        0.0     United States      High School   

  Gender  HomeOwnerFlag MaritalStatus  NumberCarsOwned      Occupation  \
0      M              1             M                0          Manual   
1      M              0             S                1    Professional   
2      M              1             M                0  Skilled Manual   
3      F              1             M                0  Skilled Manual   
4      M              0             M                2        Clerical   

   TotalChildren  YearlyIncome  
0              1         35455  
1              0         43980  
2              2         57713  
3              1         53438  
4              1         55291

In [199]:
#Separate into dependent and independent variables

X = df.iloc[:,:-1].values
y = df.iloc[:,2].values
print(y)


[ 1.  0.  0. ... nan nan nan]


In [200]:
#spliting data columns into numeric and categorical

df_num_counter=0
df_other_counter=0
for col in df:
    if (df[col].dtype)in ["int64", "float64"]:
        df_num_col=pd.DataFrame(df[col], columns=[col])
        if df_num_counter==0:
            df_num=df_num_col
        else:
            df_num=df_num.join(df_num_col)
        df_num_counter=df_num_counter+1
    else:
        df_other_col=pd.DataFrame(df[col], columns=[col])
        if df_other_counter==0:
            df_other=df_other_col
        else:
            df_other=df_other.join(df_other_col)
        df_other_counter=df_other_counter+1 

In [201]:
#reading numerical data

df_num.head()

Unnamed: 0  AveMonthSpend  BikeBuyer  HomeOwnerFlag  NumberCarsOwned  \
0           0             70        1.0              1                0   
1           1             69        0.0              0                1   
2           2            102        0.0              1                0   
3           3             49        0.0              1                0   
4           4             73        0.0              0                2   

   TotalChildren  YearlyIncome  
0              1         35455  
1              0         43980  
2              2         57713  
3              1         53438  
4              1         55291

In [113]:
#converting CountryRegionName to a categorical column for future convenience

df["CountryRegionName"]=df["CountryRegionName"].astype(str)
df["CountryRegionName"].dtype

dtype('O')

In [114]:
#converting Education to a categorical column for future convenience

df["Education"]=df["Education"].astype(str)
df["Education"].dtype

dtype('O')

In [220]:
#converting Education to a categorical column for future convenience

df["Occupation"]=df["Occupation"].astype(str)
df["Occupation"].dtype

dtype('O')

In [221]:
df.head()

Unnamed: 0  AveMonthSpend  BikeBuyer CountryRegionName        Education  \
0           0             70        1.0    United Kingdom       Bachelors    
1           1             69        0.0            Canada       Bachelors    
2           2            102        0.0            Canada       Bachelors    
3           3             49        0.0     United States  Graduate Degree   
4           4             73        0.0     United States      High School   

  Gender  HomeOwnerFlag MaritalStatus  NumberCarsOwned      Occupation  \
0      M              1             M                0          Manual   
1      M              0             S                1    Professional   
2      M              1             M                0  Skilled Manual   
3      F              1             M                0  Skilled Manual   
4      M              0             M                2        Clerical   

   TotalChildren  YearlyIncome  
0              1         35455  
1              0         43980  
2              2         57713  
3              1         53438  
4              1         55291

In [222]:
#displaying non-numeric columns data frame
df_other.head()

CountryRegionName        Education Gender MaritalStatus      Occupation
0    United Kingdom       Bachelors       M             M          Manual
1            Canada       Bachelors       M             S    Professional
2            Canada       Bachelors       M             M  Skilled Manual
3     United States  Graduate Degree      F             M  Skilled Manual
4     United States      High School      M             M        Clerical

In [223]:
df_num.isnull().sum()

Unnamed: 0            0
AveMonthSpend         0
BikeBuyer          3328
HomeOwnerFlag         0
NumberCarsOwned       0
TotalChildren         0
YearlyIncome          0
dtype: int64

In [224]:
#encoding non_numeric columns

from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
i=0
for col in df_other:
    x_enc=encoder.fit_transform(df_other[col])
    df_enc=pd.DataFrame(x_enc, columns=[col])
    if i>0:
        df_cat=df_cat.join(df_enc)
    else:
        df_cat=df_enc
    i=i+1
df_cat.head()

CountryRegionName  Education  Gender  MaritalStatus  Occupation
0                  4          0       1              0           2
1                  1          0       1              1           3
2                  1          0       1              0           4
3                  5          1       0              0           4
4                  5          2       1              0           0

In [225]:
#splitting encoded columns into binary and multi-category data frames

bin_count=0
mult_count=0

for col in df_cat:
    #print(df_cat[col].value_counts())
    if len(df_cat[col].unique())>2:
        #print (col, "has ", len(df_cat[col].unique()), " unique values")
        mult_col=df_cat[col]
        if mult_count==0:
            df_mult=pd.DataFrame(mult_col, columns=[col])
        else:
            df_mult=df_mult.join(mult_col)
        mult_count=mult_count+1
    else:
        bin_col=df_cat[col]
        if bin_count==0:
            df_bin=pd.DataFrame(bin_col, columns=[col])
        else:
            df_bin=df_bin.join(bin_col)
        bin_count=bin_count+1

In [226]:
#displaying multiple category columns
df_mult.head()

CountryRegionName  Education  Occupation
0                  4          0           2
1                  1          0           3
2                  1          0           4
3                  5          1           4
4                  5          2           0

In [227]:
#displaying binary columns
df_bin.head()

Gender  MaritalStatus
0       1              0
1       1              1
2       1              0
3       0              0
4       1              0

In [239]:
#combinig one_hot encoded and binary columns

df_complete=df_num.join(df_cat)
df_complete.head()

Unnamed: 0  AveMonthSpend  BikeBuyer  HomeOwnerFlag  NumberCarsOwned  \
0           0             70        1.0              1                0   
1           1             69        0.0              0                1   
2           2            102        0.0              1                0   
3           3             49        0.0              1                0   
4           4             73        0.0              0                2   

   TotalChildren  YearlyIncome  CountryRegionName  Education  Gender  \
0              1         35455                  4          0       1   
1              0         43980                  1          0       1   
2              2         57713                  1          0       1   
3              1         53438                  5          1       0   
4              1         55291                  5          2       1   

   MaritalStatus  Occupation  
0              0           2  
1              1           3  
2              0           4  
3              0           4  
4              0           0

In [240]:
#Filling missing values with median score

median_value=df_complete['BikeBuyer'].median()
df_complete['BikeBuyer']=df_complete['BikeBuyer'].fillna(median_value)

In [241]:
#saving data to a file
df_complete.to_csv('C:/Users/Sdeol/Desktop/all/bicyclefinal.csv')

In [242]:
#Depedendent and Independent variables

X = df_complete.iloc[:,:-1].values
y = df_complete.iloc[:,2].values
print(y)

[1. 0. 0. ... 0. 0. 0.]


In [243]:
import matplotlib.pyplot as plt
from sklearn import svm
from sklearn.svm import SVC

In [244]:
#Splitting dataset
from sklearn.cross_validation import train_test_split
x_train,x_test, y_train, y_test = train_test_split(X,y, test_size = 0.25, random_state = 42)


In [245]:
from sklearn.linear_model import LogisticRegression


In [246]:
#Import and fit LogisticRegression classifier
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression(random_state=42)
log_reg.fit(x_train, y_train.ravel())

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=42, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [247]:
#assessing model accuracy for train dataset using cross-validation

y_train_pred=log_reg.predict(x_train)
y_test_pred=log_reg.predict(x_test)
from sklearn.model_selection import cross_val_score
cross_val_score(log_reg, x_train, y_train.ravel(), cv=20, scoring="accuracy")


array([0.69806763, 0.71497585, 0.73671498, 0.69323671, 0.70460048,
       0.70702179, 0.73123487, 0.75060533, 0.73365617, 0.71186441,
       0.7433414 , 0.72154964, 0.70460048, 0.70460048, 0.72397094,
       0.80097087, 0.73300971, 0.68932039, 0.69660194, 0.69417476])

In [248]:
print (y_test_pred)

[0. 1. 0. ... 1. 0. 0.]


In [249]:
import numpy as np
import pandas as pd
prediction = pd.DataFrame(y_test_pred, columns=['predictions']).to_csv('Logreg.csv')

In [250]:
y_test_pred=log_reg.predict(x_test)
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test_pred, y_test.ravel())
print (accuracy)

0.7058823529411765


In [251]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

model = RandomForestClassifier()
model.fit(x_train, y_train)
y_predict = model.predict(x_test)

accuracy_score(y_test, y_predict)

print (y_predict)

[1. 1. 0. ... 1. 0. 0.]


In [252]:
import numpy as np
import pandas as pd
submission2 = pd.DataFrame(y_predict, columns=['BikeBuyer']).to_csv('Submission2.csv')

In [253]:
nccf=NeverChurnClassifier()
y_train_nccf_pred=nccf.predict(x_train)
n_correct=sum(y_train_nccf_pred==y_train)
n_correct
print("Baseline Accuracy: ", n_correct/len(y_train_pred))

Baseline Accuracy:  [1. 0. 0. ... 1. 1. 1.]


In [254]:
#import the necessary module
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

#create an object of the type GaussianNB
gnb = GaussianNB()

#train the algorithm on training data and predict using the testing data
pred = gnb.fit(x_train, y_train).predict(x_test)
#print(pred.tolist())

#print the accuracy score of the model
print("Naive-Bayes accuracy : ",accuracy_score(y_test, pred, normalize = True))

Naive-Bayes accuracy :  0.7861292665214233


In [255]:
print(pred)

[0. 1. 0. ... 1. 0. 0.]


In [256]:
import numpy as np
import pandas as pd
Submission3 = pd.DataFrame(pred, columns=['BikeBuyer']).to_csv('Gaussian.csv')

In [257]:
#import the necessary modules
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score

#create an object of type LinearSVC
svc_model = LinearSVC(random_state=42)

#train the algorithm on training data and predict using the testing data
pred2 = svc_model.fit(x_train, y_train).predict(x_test)

#print the accuracy score of the model
print("LinearSVC accuracy : ",accuracy_score(y_test, pred2, normalize = True))

LinearSVC accuracy :  0.659041394335512


In [258]:
print (pred2)

[0. 0. 0. ... 0. 0. 0.]


In [182]:
import numpy as np
import pandas as pd
prediction = pd.DataFrame(pred2, columns=['BikeBuyer']).to_csv('SVC.csv')

In [260]:
#import necessary modules
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

#create object of the lassifier
neigh = KNeighborsClassifier(n_neighbors=3)

#Train the algorithm
neigh.fit(x_train, y_train)

# predict the response
pred1 = neigh.predict(x_test)

# evaluate accuracy
print ("KNeighbors accuracy score : ",accuracy_score(y_test, pred1))

KNeighbors accuracy score :  0.6877269426289034


In [261]:
print (pred1)

[0. 0. 0. ... 0. 1. 1.]


In [183]:
import numpy as np
import pandas as pd
prediction = pd.DataFrame(pred1, columns=['BikeBuyer']).to_csv('Knearest.csv')